#MOSTRAR EL PORCENTAJE MAS ALTOS DE LOS PAISES EN INFECCION DE COVID
SELECT LOCATION , POPULATION ,MAX(TOTAL_CASES) MAXCASES, 
	ROUND(MAX(TOTAL_CASES/POPULATION)*100,3) PERCENTPOPULATIONINFECTED 
FROM COVIDDEATH C 
GROUP BY LOCATION,POPULATION 
ORDER BY PERCENTPOPULATIONINFECTED DESC;


#MOSTRAR EL PORCENTAJE MAS ALTOS DE LOS PAISES DE MUERTE POR COVID
SELECT LOCATION ,MAX(TOTAL_CASES) MAXCASES ,MAX(TOTAL_DEATHS) MAXDEATH, 
	ROUND(MAX(TOTAL_DEATHS /TOTAL_CASES)*100,3) PERCENTDEATH 
FROM COVIDDEATH C 
GROUP BY LOCATION
ORDER BY PERCENTDEATH DESC;


# DATOS RELACIONADOS CON EL PERU
SELECT * 
FROM COVIDDEATH C 
#WHERE CONTINENT  = 'SOUTH AMERICA'
WHERE  LOCATION  = 'PERU'
ORDER BY 1,2;


#MOSTRAR LA PROBABILIDAD DE MORIR SI CONTRAES EL COVID EN EL PERU
SELECT `DATE`  ,TOTAL_CASES ,TOTAL_DEATHS , ROUND((TOTAL_DEATHS/TOTAL_CASES*100),3) PERCENT_DEATH
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU'
GROUP BY `DATE`;  


#AGRUPAR POR AÑO Y MES 
SELECT DATE_FORMAT(`DATE` , '%Y-%M') ,TOTAL_CASES ,TOTAL_DEATHS , ROUND((TOTAL_DEATHS/TOTAL_CASES*100),3) PERCENT_DEATH
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU'
GROUP BY YEAR(`DATE`) , MONTH(`DATE`);


# MOSTRAR LA PROBALIDIDAD QUE LA POPLACION OBTENGA EL COVID EN EL PERU
SELECT `DATE` ,TOTAL_CASES ,POPULATION ,
	ROUND((TOTAL_CASES/POPULATION*100),3) PERCENT_CONT 
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU';


#AGRUPAR POR AÑO Y MES
SELECT DATE_FORMAT(`DATE` , '%Y-%M') YEARMONTH,TOTAL_CASES ,POPULATION ,
	ROUND((TOTAL_CASES/POPULATION*100),3) PERCENT_CONT
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU'
GROUP BY YEAR(`DATE`) , MONTH(`DATE`);


# MOSTRAR LA PROBABILIDAD POR MES Y AÑO DE MORIR DE COVID EN SUDAMERICA
SELECT LOCATION ,`DATE` ,TOTAL_CASES ,TOTAL_DEATHS,
	ROUND((TOTAL_DEATHS/TOTAL_CASES*100),3) PERCENT_DEATH
FROM COVIDDEATH C 
WHERE CONTINENT  = 'SOUTH AMERICA'
GROUP BY LOCATION,YEAR (`DATE`), MONTH (`DATE`)
ORDER BY LOCATION ,YEAR (`DATE`), MONTH (`DATE`)




