#MOSTRAR EL PORCENTAJE MAS ALTOS DE LOS PAISES EN INFECCION DE COVID
SELECT LOCATION , POPULATION ,MAX(TOTAL_CASES) MAXCASES, 
	ROUND(MAX(TOTAL_CASES/POPULATION)*100,3) PERCENTPOPULATIONINFECTED 
FROM COVIDDEATH C 
GROUP BY LOCATION,POPULATION 
ORDER BY PERCENTPOPULATIONINFECTED DESC;


# LOS PAISES CON MAYOR NUMERO DE MUERTES POR COVID
SELECT LOCATION , MAX(CAST(TOTAL_DEATHS AS UNSIGNED)) MAXDEATH  -- IN SQL IS CAST(__ AS INT) 
FROM COVIDDEATH C 
WHERE CONTINENT IS NOT NULL 
GROUP BY LOCATION 
ORDER BY MAXDEATH DESC;


#NUMERO CON MAYOR NUMERO DE MUERTES POR CONTINENTE
SELECT CONTINENT , MAX(CAST(TOTAL_DEATHS AS UNSIGNED)) MAXDEATH
FROM COVIDDEATH C 
WHERE CONTINENT IS NOT NULL 
GROUP BY CONTINENT 
ORDER BY MAXDEATH DESC;


#OBSERVAR LA DIVISION DEL CONTINENTE AMERICANO 
-- FORMA 1
SELECT DISTINCT LOCATION,
	(CASE 
		WHEN CONTINENT = 'NORTH AMERICA' THEN 1 
			ELSE  0 END)  AS 'NORTH AMERICA',
	(CASE 
		WHEN CONTINENT = 'SOUTH AMERICA' THEN 1 
			ELSE 0 END ) AS 'SOUTH AMERICA'
FROM COVIDDEATH C 
WHERE CONTINENT LIKE '%AMERICA%'

-- FORMA 2
SELECT DISTINCT LOCATION,
	CASE
		WHEN CONTINENT = 'SOUTH AMERICA' THEN 'SOUTH' 
			ELSE 'NORTH' END  AS 'AMERICA'
FROM COVIDDEATH C 
WHERE CONTINENT LIKE '%AMERICA%'

#NUMERO TOTAL DE CASOS, MUERTES Y PORCENTAJE MUNDIAL
SELECT SUM(TOTAL_CASES) TOTAL_CASES , SUM(TOTAL_DEATHS) TOTAL_DEATHS ,
	ROUND(SUM(TOTAL_DEATHS)/SUM(TOTAL_CASES)*100,3) AS DEATHPERCENT  
FROM COVIDDEATH C 


# DATOS RELACIONADOS CON EL PERU
SELECT * 
FROM COVIDDEATH C 
#WHERE CONTINENT  = 'SOUTH AMERICA'
WHERE  LOCATION  = 'PERU'
ORDER BY 1,2;


#MOSTRAR LA PROBABILIDAD DE MORIR SI CONTRAES EL COVID EN EL PERU
SELECT `DATE`  ,TOTAL_CASES ,TOTAL_DEATHS , ROUND((TOTAL_DEATHS/TOTAL_CASES*100),3) PERCENT_DEATH
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU'
GROUP BY `DATE`;  


#AGRUPAR POR AÑO Y MES 
SELECT DATE_FORMAT(`DATE` , '%Y-%M') ,TOTAL_CASES ,TOTAL_DEATHS , ROUND((TOTAL_DEATHS/TOTAL_CASES*100),3) PERCENT_DEATH
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU'
GROUP BY YEAR(`DATE`) , MONTH(`DATE`);


# MOSTRAR LA PROBALIDIDAD QUE LA POPLACION OBTENGA EL COVID EN EL PERU
SELECT `DATE` ,TOTAL_CASES ,POPULATION ,
	ROUND((TOTAL_CASES/POPULATION*100),3) PERCENT_CONT 
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU';


#AGRUPAR POR AÑO Y MES
SELECT DATE_FORMAT(`DATE` , '%Y-%M') YEARMONTH,TOTAL_CASES ,POPULATION ,
	ROUND((TOTAL_CASES/POPULATION*100),3) PERCENT_CONT
FROM COVIDDEATH C 
WHERE LOCATION = 'PERU'
GROUP BY YEAR(`DATE`) , MONTH(`DATE`);


# MOSTRAR LA PROBABILIDAD POR MES Y AÑO DE MORIR DE COVID EN SUDAMERICA
SELECT LOCATION ,`DATE` ,TOTAL_CASES ,TOTAL_DEATHS,
	ROUND((TOTAL_DEATHS/TOTAL_CASES*100),3) PERCENT_DEATH
FROM COVIDDEATH C 
WHERE CONTINENT  = 'SOUTH AMERICA'
GROUP BY LOCATION,YEAR (`DATE`), MONTH (`DATE`)
ORDER BY LOCATION ,YEAR (`DATE`), MONTH (`DATE`)


## COVIDDEATH VS COVIDVAC
SELECT D.CONTINENT ,D.LOCATION ,D.`DATE`, D.POPULATION , V.NEW_VACCINATIONS,
SUM(V.NEW_VACCINATIONS) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS PARTITION_VAC
FROM COVIDDEATH D JOIN COVIDVAC V
ON D.LOCATION = V.LOCATION AND D.`DATE` = V.`DATE` 
WHERE D.CONTINENT IS NOT NULL 
GROUP BY D.LOCATION ,D.`DATE`
ORDER BY 2,3;


# USAR LA COLUMNA AGREGADA
-- FORMA 1 
WITH VACVSPOP (CONTINENT,LOCATION,DATE,POPULATION,NEW_VACCINATIONS,PARTITION_VAC)
AS 
(
SELECT D.CONTINENT ,D.LOCATION ,D.`DATE`, D.POPULATION , V.NEW_VACCINATIONS,
SUM(V.NEW_VACCINATIONS) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS PARTITION_VAC
FROM COVIDDEATH D JOIN COVIDVAC V
ON D.LOCATION = V.LOCATION AND D.`DATE` = V.`DATE` 
WHERE D.CONTINENT IS NOT NULL 
GROUP BY D.LOCATION ,D.`DATE`
              -- ORDER BY 2,3;
)
SELECT *,(PARTITION_VAC/POPULATION )* 100 AS PERCENTROLLING
FROM VACVSPOP


-- TEMP TABLE (REVISAR SOBRE ESTE TEMA NO ME SALE XDDD)


# CREAR VIEW

CREATE VIEW PERCENTPOPULATIONVACCINATED AS 
SELECT D.CONTINENT ,D.LOCATION ,D.`DATE`, D.POPULATION , V.NEW_VACCINATIONS,
SUM(V.NEW_VACCINATIONS) OVER (PARTITION BY D.LOCATION ORDER BY D.LOCATION , D.DATE) AS PARTITION_VAC
FROM COVIDDEATH D JOIN COVIDVAC V
ON D.LOCATION = V.LOCATION AND D.`DATE` = V.`DATE` 
WHERE D.CONTINENT IS NOT NULL 

SELECT * FROM PERCENTPOPULATIONVACCINATED 
